"""Markdown → PDF export using xhtml2pdf (pure Python).

xhtml2pdf can choke on some Unicode emoji; we substitute the worst
offenders with text equivalents before rendering. If even that fails the
caller can fall back to a plain HTML download.
"""
from __future__ import annotations

import io
import re

import markdown as _md


_PDF_CSS = """
@page {
    size: A4;
    margin: 1.4cm 1.2cm 1.6cm 1.2cm;
    @frame footer_frame {
        -pdf-frame-content: footer_content;
        left: 1.2cm; right: 1.2cm;
        top: 27.0cm; height: 0.6cm;
    }
}
body {
    font-family: 'Helvetica', sans-serif;
    color: #2a2a2c;
    font-size: 10pt;
    line-height: 1.45;
}
h1 { color: #1a1a1c; font-size: 22pt; margin-top: 0; }
h2 { color: #a8862e; font-size: 14pt; margin-top: 18pt; padding-bottom: 4pt; border-bottom: 1pt solid #d4a843; }
h3 { color: #444; font-size: 12pt; }
strong { color: #1a1a1c; }
em { color: #555; font-style: italic; }
hr { border: 0; border-top: 0.5pt solid #d0d0d0; margin: 12pt 0; }
ul, ol { margin: 6pt 0 6pt 18pt; }
li { margin-bottom: 3pt; }
code, pre {
    font-family: 'Courier New', monospace;
    background: #f5f5f5;
    color: #3a3a3a;
    padding: 1pt 3pt;
    border-radius: 2pt;
    font-size: 9.5pt;
}
blockquote {
    border-left: 3pt solid #d4a843;
    margin: 8pt 0;
    padding: 4pt 8pt;
    background: #fff8e8;
    color: #555;
    font-style: italic;
}
.footer {
    font-size: 8pt;
    color: #888;
    text-align: center;
}
"""


# Emoji that xhtml2pdf's default font can't render → text fallback.
_EMOJI_FALLBACKS = {
    "💪": "[Strength]",
    "📊": "[Volume]",
    "📅": "[Adherence]",
    "🏆": "[Achievements]",
    "💬": "[Coach]",
    "😂": "[Quotes]",
    "🏋️": "[IronTrail]",
    "🏋": "[IronTrail]",
    "📤": "[Upload]",
    "📝": "[Note]",
    "💾": "[Save]",
    "⬇️": "[Download]",
    "📄": "[PDF]",
    "📋": "[Copy]",
    "💀": "[Shame]",
    "🔥": "[Streak]",
    "💎": "[Diamond]",
    "🌊": "[Wave]",
    "💯": "[100]",
    "🥏": "[Disc]",
    "🪞": "[Mirror]",
    "🦵": "[Leg]",
    "🏔": "[Mountain]",
    "🪦": "[Headstone]",
    "🪨": "[Rock]",
    "🗿": "[Statue]",
    "🌱": "[Sprout]",
    "🌳": "[Tree]",
    "🌈": "[Rainbow]",
    "📚": "[Books]",
    "🛡": "[Shield]",
    "⚡": "[Bolt]",
}


def _strip_emoji(s: str) -> str:
    for src, dst in _EMOJI_FALLBACKS.items():
        s = s.replace(src, dst)
    # Strip any remaining 4-byte emoji blocks
    s = re.sub(
        "["
        "\U0001F000-\U0001FFFF"
        "\u2600-\u27BF"
        "\u2300-\u23FF"
        "\u2700-\u27BF"
        "\uFE00-\uFE0F"
        "]+",
        "",
        s,
    )
    return s


def markdown_to_pdf(md: str, *, title: str = "IronTrail Review") -> bytes:
    """Render Markdown to a PDF byte string.

    Raises ``RuntimeError`` if xhtml2pdf fails — the caller can then fall
    back to a plain HTML download.
    """
    from xhtml2pdf import pisa

    safe_md = _strip_emoji(md)

    # Drop YAML frontmatter (between leading --- pairs) — it's not useful in PDF
    if safe_md.startswith("---"):
        end = safe_md.find("\n---", 3)
        if end != -1:
            safe_md = safe_md[end + 4 :].lstrip()

    html_body = _md.markdown(safe_md, extensions=["tables", "fenced_code"])
    html = (
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<title>{title}</title><style>{_PDF_CSS}</style></head>"
        f"<body>{html_body}"
        "<div id='footer_content' class='footer'>"
        "Generated by IronTrail · iron-trail.streamlit.app"
        "</div></body></html>"
    )

    buf = io.BytesIO()
    result = pisa.CreatePDF(src=html, dest=buf, encoding="utf-8")
    if result.err:
        raise RuntimeError(f"xhtml2pdf reported {result.err} errors")
    return buf.getvalue()
